### PR TITLE
Update library to latest maui preview version (5.794)

### PR DESCRIPTION
**Pull request by zleao**
Updated the Prism Library to use the latest maui preview version (5.794) and corrected some namespaces that changed
Re-created the samples using the new templates (using now just one WinUI project)

### CODE REVIEW

**Comment by dansiegel** [comment]
Thanks for the PR @zleao I actually already had Prism.Maui updated for preview 5, I'm just experimenting with some possible changes to the API before I release the update

**Comment by zleao** [comment]
Do you have an idea of when a new release will be available?

**Comment by dansiegel** [comment]
like everyone else I have the same issues with tooling not working which just means it takes longer to properly validate before I publish. Also I have been giving a little higher priority to a few other libraries. I will get an update for Prism.Maui out as soon as I can, but in the mean time the existing preview should still be compatible with Maui preview 5

**Comment by zleao** [comment]
The current package is not compatible with MAUI preview 5, due to some namespace changes. But no worries. And don't get my question wrong. I was just curious. I do know the tooling is still with some issues and I do thank you for all your effort.

**Comment by dansiegel** [comment]
well that certainly is frustrating, and I appreciate you letting me know about the break.

**Comment by dansiegel** [comment]
I have re-enabled issues on the repo so that in the future we can discuss these sorts of things.

**Pull request closed without merging**
