### PR TITLE
Made changes to apply to Maui RC-1 release

### PR DESCRIPTION
**Pull request by jBijsterboschNL**

### CODE REVIEW

**Comment by UweReisewitz** [comment]
Hi,
Lines 47-50 are also not needed anymore. After that the Windows Deploy complained about the missing Splash Screen (see my comment here https://github.com/dansiegel/Prism.Maui/issues/14#issue-1203293101) and the old one in NavigationRegistrationExtensions is still there.
Do you get the stackoverflow, too?

Best Regards
Uwe

**Comment by jBijsterboschNL** [comment]
> Hi,
> Lines 47-50 are also not needed anymore. After that the Windows Deploy complained about the missing Splash Screen (see my comment here https://github.com/dansiegel/Prism.Maui/issues/14#issue-1203293101) and the old problem in NavigationRegistrationExtensions is still there.
> Do you get the stackoverflow, too?
> 
> Best Regards
> Uwe

I'm also experiencing the stackoverflow as you've discribed. I'll remove those lines as well this week. And also have a look at the splash screen issue for Windows. Cheets

**Comment by jBijsterboschNL** [comment]
@UweReisewitz I've updated the Pull Request, removing the unnecessary Windows configuration from the csproj file and fixing the Windows deploy, which gave an error that the splash screen could not be found.

But still the stackoverflow on PrismServiceProviderFactory.CreateScope() remains. Hopefully @dansiegel is able to have another look at this.

Other than that, the branch is now up-to-date with Maui RC-1 :)

**Comment by dansiegel** [comment]
thanks @jBijsterboschNL I just got back from vacation last night, I'll try to take a look at this later today

**Pull request merged**
