### PR TITLE
RC 2 - Preview 9

### LINKED ISSUE #2: Error: "Method not found: Microsoft.Maui.Hosting.IAppHostBuilder"
Hello, I am trying to implement **Prism.Maui** a test Maui project. I have installed **Prism.DryIoc.Maui 8.1.27-alpha** from Nuget. My implement codes is located below. When I debug project to Android Emulator I am getting error. I think I am overlooking some things. Thank you in advance.

**Error**
`
System.MissingMethodException: 'Method not found: Microsoft.Maui.Hosting.IAppHostBuilder Microsoft.Maui.Hosting.AppHostBuilderExtensions.UseMauiApp<!0>(Microsoft.Maui.Hosting.IAppHostBuilder)'`

Error

**Startup.cs**

```
using Microsoft.Maui;
using Microsoft.Maui.Hosting;
using Prism;

namespace MauiTest
{
    public class Startup : IStartup
    {
        public void Configure(IAppHostBuilder appBuilder)
        {
            appBuilder
                .UsePrismApplication<App>(x => x.UseDryIoc())
                .ConfigureFonts(fonts =>
                {
                    fonts.AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
                });
        }
    }
}
```

**App.cs**

```
using Microsoft.Maui;
using Microsoft.Maui.Controls.PlatformConfiguration.WindowsSpecific;
using Prism;
using Prism.Ioc;
using Prism.Navigation;
using System.Threading.Tasks;

namespace MauiTest
{
    public partial class App : PrismApplication
    {
        public App(IContainerExtension container)
            : base(container)
        {
        }
        
        protected async override Task OnWindowCreated(IActivationState activationState)
        {
            Microsoft.Maui.Controls.Compatibility.Forms.Init(activationState);

            this.On<Microsoft.Maui.Controls.PlatformConfiguration.Windows>()
                .SetImageDirectory("Assets");

            await NavigationService.NavigateAsync("/MainPage");
        }

        protected override void RegisterTypes(IContainerRegistry containerRegistry)
        {
            containerRegistry.RegisterForNavigation<MainPage>();
        }
    }
}
```

**App.xaml**
```

<prism:PrismApplication xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
			 xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
			 xmlns:local="clr-namespace:MauiTest"
             xmlns:prism="clr-namespace:Prism;assembly=Prism.Maui"
			 x:Class="MauiTest.App">
    <prism:PrismApplication.Resources>
        <ResourceDictionary>
            <Color x:Key="PageBackgroundColor">#512bdf</Color>
            <Color x:Key="PrimaryTextColor">White</Color>

            <Style TargetType="Label">
                <Setter Property="TextColor" Value="{DynamicResource PrimaryTextColor}" />
                <Setter Property="FontFamily" Value="OpenSansRegular" />
            </Style>

            <Style TargetType="Button">
                <Setter Property="TextColor" Value="{DynamicResource PrimaryTextColor}" />
                <Setter Property="FontFamily" Value="OpenSansRegular" />
                <Setter Property="BackgroundColor" Value="#2b0b98" />
                <Setter Property="Padding" Value="14,10" />
            </Style>

        </ResourceDictionary>
    </prism:PrismApplication.Resources>
</prism:PrismApplication>

```

### PR DESCRIPTION
**Pull request by dansiegel**
# Description

This is the cumulative update for RC2 (Maui Preview 9).

- closes #2

## Changes

While the changes for Preview 7 had originally aligned Prism.Maui's PrismApplication with the same startup process that you would be used to with Prism.Forms, Prism.Wpf, or Prism.Uno, the introduction of MauiProgram and removal of Maui's IStartup changes how this needs to work. The proposed API introduces a PrismAppBuilder which is built off of the MauiAppBuilder. This provides a similar experience to what you would see when working with builders in an AspNetCore app. 

The proposed PrismAppBuilder exposes methods and extensions to Configure the Module Catalog, and Register Types with Prism's IContainerRegistry, both of which would typically be part of PrismApplication. Within Prism.Maui a `UsePrismApp` extension is exposed that takes an `IContainerExtension`. This allows anyone to implement Prism's IContainerExtension and use their specific container. For DryIoc a parameterless extension makes it easy to simply use the DryIocContainerExtension.

```cs
public static class MauiProgram
{
    public static MauiApp CreateMauiApp()
    {
        var builder = MauiApp.CreateBuilder()
            .UsePrismApp<App>()
            .ConfigureModuleCatalog(moduleCatalog =>
            {
                moduleCatalog.AddModule<MauiAppModule>();
            })
            .RegisterTypes(containerRegistry =>
            {
                containerRegistry.RegisterForNavigation<MainPage>();
            })
            .MauiBuilder
            .ConfigureFonts(fonts =>
            {
                fonts.AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
            });

        return builder.Build();
    }
}
```

With this the implementation of PrismApplication itself becomes very simple. PrismApplication overrides the IApplication implementation from Maui so that we can properly manage the Window create. In this process where you might have done your Initial Navigation in `OnInitialized` you would now do the Navigation in `OnWindowCreated`. This gives you access to the activationState and will set the content of the window. Note that Multi-Windowed experiences still need to be figured out for Maui as a whole and this may change as our understanding of what a Multi-Windowed Maui Application looks like. I would expect this API to change as the Maui team figures that out themselves.

```cs
public partial class App : PrismApplication
{
    public App()
    {
        InitializeComponent();
    }

    protected override async Task OnWindowCreated(IActivationState activationState)
    {
        await NavigationService.NavigateAsync("MainPage");
    }
}
```

### CODE REVIEW

**Comment by IndexOutOfLimit** [comment]
Can you please let me know when this will be merged and we can use Prism for MAUI

**Comment by DamianSuess** [comment]
Looking forward to this update. Thank you, Dan, for staying on top of things.

**Comment by dansiegel** [comment]
hi @jBijsterboschNL I would suggest sending me a DM on Discord as we can better coordinate from there

**Comment by DamianSuess** [comment]
🍻  thank you Dan for this PR! Can't wait to test drive it

**Pull request closed without merging**
