### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by dansiegel**
# Description

Updates various dependencies. Updates the Sample Project properties to match the latest changes to the Maui Template

### CODE REVIEW

**Comment by UweReisewitz** [comment]
Thanks for the update. Unfortunately we are still plagued with the famous 
`The target "CopyLocalFilesOutputGroup" does not exist in the project.`
error. 

So it's not possible to compile and run the PrismMauiDemo (and probably any other app that likes to use Prism.Maui).

This is still present in Preview 6.

**Comment by dansiegel** [comment]
@UweReisewitz are you doing this from Visual Studio for Mac? I have no issues compiling from Visual Studio 2022 on Windows.

**Comment by UweReisewitz** [comment]
No, I'm on Windows and I had cloned the repository from scratch. Do you have Preview 6?
I'll try again today.

**Comment by dansiegel** [comment]
That is strange because I have no problems with compiling and deploying the Sample app in Visual Studio 2022 (17.2 Pre6). Which is not to say that the app actually runs. There is an error which as best as I can tell has to do with Prism and Maui both setting Scopes. I still need to figure that one out with the MAUI team.

**Comment by UweReisewitz** [comment]
This is my Build Log (Rebuild with PrismMauiDemo/Windows set as startup project)
VS 17.2 Preview 6, Fresh Clone of reprository, fresh dowloaded NuGet packages:
```
Rebuild started...
Restored C:\Users\ur\Source\Repos\Prism.Maui\sample\MauiModule\MauiModule.csproj (in 25 ms).
Restored C:\Users\ur\Source\Repos\Prism.Maui\src\Prism.Maui\Prism.Maui.csproj (in 25 ms).
Restored C:\Users\ur\Source\Repos\Prism.Maui\src\Prism.DryIoc.Maui\Prism.DryIoc.Maui.csproj (in 25 ms).
Restored C:\Users\ur\Source\Repos\Prism.Maui\tests\Prism.Maui.Tests\Prism.Maui.Tests.csproj (in 262 ms).
Restored C:\Users\ur\Source\Repos\Prism.Maui\sample\PrismMauiDemo\PrismMauiDemo.csproj (in 580 ms).
1>------ Rebuild All started: Project: Prism.Maui, Configuration: Debug Any CPU ------
1>You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
1>C:\Users\ur\Source\Repos\Prism.Maui\src\Prism.Maui\Navigation\PageNavigationService.cs(1078,30,1078,32): warning CS0168: The variable 'ex' is declared but never used
1>Prism.Maui -> C:\Users\ur\Source\Repos\Prism.Maui\src\Prism.Maui\bin\Debug\net6.0\Prism.Maui.dll
1>Successfully created package 'C:\Users\ur\Source\Repos\Prism.Maui\Artifacts\Prism.Maui.8.1.69-alpha.nupkg'.
1>Successfully created package 'C:\Users\ur\Source\Repos\Prism.Maui\Artifacts\Prism.Maui.8.1.69-alpha.snupkg'.
1>Done building project "Prism.Maui.csproj".
2>------ Rebuild All started: Project: MauiModule, Configuration: Debug Any CPU ------
3>------ Rebuild All started: Project: Prism.Maui.Tests, Configuration: Debug Any CPU ------
4>------ Rebuild All started: Project: Prism.DryIoc.Maui, Configuration: Debug Any CPU ------
3>You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
2>You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
3>Prism.Maui.Tests -> C:\Users\ur\Source\Repos\Prism.Maui\tests\Prism.Maui.Tests\bin\Debug\net6.0\Prism.Maui.Tests.dll
2>MauiModule -> C:\Users\ur\Source\Repos\Prism.Maui\sample\MauiModule\bin\Debug\net6.0\MauiModule.dll
4>Prism.DryIoc.Maui -> C:\Users\ur\Source\Repos\Prism.Maui\src\Prism.DryIoc.Maui\bin\Debug\net6.0\Prism.DryIoc.Maui.dll
4>Successfully created package 'C:\Users\ur\Source\Repos\Prism.Maui\Artifacts\Prism.DryIoc.Maui.8.1.69-alpha.nupkg'.
4>Successfully created package 'C:\Users\ur\Source\Repos\Prism.Maui\Artifacts\Prism.DryIoc.Maui.8.1.69-alpha.snupkg'.
5>------ Rebuild All started: Project: PrismMauiDemo, Configuration: Debug Any CPU ------
5>PrismMauiDemo -> C:\Users\ur\Source\Repos\Prism.Maui\sample\PrismMauiDemo\bin\Debug\net6.0-windows10.0.19041\win10-x64\PrismMauiDemo.dll
5>C:\Program Files\dotnet\packs\Microsoft.Maui.Sdk\6.0.300-rc.2.5513\Sdk\WinUI.NetCore.targets(188,5): error MSB4057: The target "CopyLocalFilesOutputGroup" does not exist in the project.  C:\Program Files\dotnet\packs\Microsoft.Maui.Sdk\6.0.300-rc.2.5513\Sdk\WinUI.NetCore.targets
5>Done building project "MauiModule.csproj" -- FAILED.
5>C:\Program Files\dotnet\packs\Microsoft.Maui.Sdk\6.0.300-rc.2.5513\Sdk\WinUI.NetCore.targets(188,5): error MSB4057: The target "CopyLocalFilesOutputGroup" does not exist in the project.  C:\Program Files\dotnet\packs\Microsoft.Maui.Sdk\6.0.300-rc.2.5513\Sdk\WinUI.NetCore.targets
5>Done building project "Prism.DryIoc.Maui.csproj" -- FAILED.
5>C:\Program Files\dotnet\packs\Microsoft.Maui.Sdk\6.0.300-rc.2.5513\Sdk\WinUI.NetCore.targets(188,5): error MSB4057: The target "CopyLocalFilesOutputGroup" does not exist in the project.  C:\Program Files\dotnet\packs\Microsoft.Maui.Sdk\6.0.300-rc.2.5513\Sdk\WinUI.NetCore.targets
5>Done building project "Prism.Maui.csproj" -- FAILED.
========== Rebuild All: 4 succeeded, 1 failed, 0 skipped ==========

```

**Comment by UweReisewitz** [comment]
@dansiegel Regarding windows:
I got it running but only by changing the references from project to aseembly and adding the Prism.Core and the DryIoc NuGets. Then it compiled, deployed and ran. Yeehaa.

Are you on a Mac? This might be a specific problem of the Windows Preview...

**Comment by dansiegel** [comment]
I'm exclusively using Visual Studio 2022 Preview 6 on Windows.

**Pull request merged**
